import type { ExpoConfig, ConfigContext } from 'expo/config';

// Read env-driven values once so we can validate them in one place later.
const SENTRY_DSN = process.env.SENTRY_DSN ?? '';
const SUPABASE_URL = process.env.SUPABASE_URL ?? '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY ?? '';

// Values surfaced to the app at runtime via `expo-constants`.
// Read with the typed helper in src/lib/env.ts — do not pull from
// Constants directly elsewhere.
const extra = {
  sentryDsn: SENTRY_DSN,
  supabaseUrl: SUPABASE_URL,
  supabaseAnonKey: SUPABASE_ANON_KEY,
  // EAS Build / EAS Submit use this to identify the project. Generated by
  // `eas init`; do not change.
  eas: {
    projectId: '44bbb4b0-93df-42b3-9021-e6af5733b50c',
  },
};

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: 'BidaWash',
  slug: 'bidawash',
  scheme: 'bidawash',
  version: '1.0.0',
  orientation: 'portrait',
  icon: './assets/icon.png',
  userInterfaceStyle: 'automatic',
  newArchEnabled: true,
  splash: {
    image: './assets/splash.png',
    resizeMode: 'cover',
    backgroundColor: '#E30613',
  },
  // EAS Update (over-the-air JS bundle updates). The URL is tied to the
  // EAS projectId above; runtimeVersion=appVersion means we ship a new
  // native binary every time the user-facing version bumps.
  updates: {
    url: 'https://u.expo.dev/44bbb4b0-93df-42b3-9021-e6af5733b50c',
  },
  runtimeVersion: {
    policy: 'appVersion',
  },
  assetBundlePatterns: ['**/*'],
  ios: {
    bundleIdentifier: 'com.bidawash.app',
    supportsTablet: false,
    // Per-permission usage strings get added here as features are built.
    infoPlist: {
      ITSAppUsesNonExemptEncryption: false,
    },
    // iOS 17.4+ Privacy Manifest. Expo SDK 52 auto-generates entries for
    // its own modules; the declarations here cover data types the app
    // itself collects and standard React Native "required reason" APIs.
    // If a third-party SDK adds new declarations we merge them at build.
    privacyManifests: {
      NSPrivacyCollectedDataTypes: [
        {
          NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypeEmailAddress',
          NSPrivacyCollectedDataTypeLinked: true,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: [
            'NSPrivacyCollectedDataTypePurposeAppFunctionality',
          ],
        },
        {
          NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypeName',
          NSPrivacyCollectedDataTypeLinked: true,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: [
            'NSPrivacyCollectedDataTypePurposeAppFunctionality',
          ],
        },
        {
          NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypePhoneNumber',
          NSPrivacyCollectedDataTypeLinked: true,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: [
            'NSPrivacyCollectedDataTypePurposeAppFunctionality',
          ],
        },
        {
          NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypeCoarseLocation',
          NSPrivacyCollectedDataTypeLinked: false,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: [
            'NSPrivacyCollectedDataTypePurposeAppFunctionality',
          ],
        },
        {
          NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypeCrashData',
          NSPrivacyCollectedDataTypeLinked: false,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: [
            'NSPrivacyCollectedDataTypePurposeAnalytics',
          ],
        },
        {
          NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypePerformanceData',
          NSPrivacyCollectedDataTypeLinked: false,
          NSPrivacyCollectedDataTypeTracking: false,
          NSPrivacyCollectedDataTypePurposes: [
            'NSPrivacyCollectedDataTypePurposeAnalytics',
          ],
        },
      ],
      NSPrivacyAccessedAPITypes: [
        {
          NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryUserDefaults',
          NSPrivacyAccessedAPITypeReasons: ['CA92.1'],
        },
        {
          NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryFileTimestamp',
          NSPrivacyAccessedAPITypeReasons: ['C617.1'],
        },
        {
          NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategorySystemBootTime',
          NSPrivacyAccessedAPITypeReasons: ['35F9.1'],
        },
        {
          NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryDiskSpace',
          NSPrivacyAccessedAPITypeReasons: ['E174.1'],
        },
      ],
      NSPrivacyTracking: false,
      NSPrivacyTrackingDomains: [],
    },
  },
  android: {
    package: 'com.bidawash.app',
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      backgroundColor: '#FFFFFF',
    },
  },
  web: {
    favicon: './assets/favicon.png',
  },
  plugins: [
    'expo-asset',
    'expo-font',
    'expo-secure-store',
    // Foreground-only location for the "find nearest branch" flow.
    // NSLocationWhenInUseUsageDescription (iOS) and ACCESS_COARSE/FINE_LOCATION
    // (Android) are added by the plugin automatically.
    [
      'expo-location',
      {
        locationWhenInUsePermission:
          'BidaWash uses your location to show the nearest branch. Location is used only when you tap "Sort by nearest" and never leaves your device.',
      },
    ],
    // Pins Kotlin to a version compatible with the Compose Compiler
    // bundled by Expo SDK 52's expo-modules-core. Without this, the
    // Android Gradle build fails with a Kotlin/Compose mismatch.
    [
      'expo-build-properties',
      {
        android: {
          kotlinVersion: '1.9.25',
        },
      },
    ],
    // NOTE: @sentry/react-native/expo plugin removed for now. Runtime
    // crash reporting still works via src/lib/sentry.ts (it reads the
    // DSN at runtime and no-ops if empty). The plugin only handles
    // build-time source map upload, which requires a Sentry org + auth
    // token we haven't set up yet. Re-add it once you sign up at
    // sentry.io and push SENTRY_ORG / SENTRY_PROJECT / SENTRY_AUTH_TOKEN
    // as EAS secrets.
  ],
  extra,
});
