-- seed/faqs.sql
-- Populates public.faqs with the customer-facing FAQ list maintained by
-- the BidaWash team. Source of truth is docs/faqs.csv — regenerate this
-- file when the CSV changes.
--
-- Re-runnable: `on conflict (id) do update` upserts each row, so pasting
-- this into the Supabase SQL editor repeatedly is safe. Rows removed
-- from the CSV are NOT auto-deleted here; delete them by hand or drop
-- and re-run the whole seed.
--
-- Requires migration 0003_favorites_and_faqs.sql (which creates the
-- public.faqs table and its RLS policy).

insert into public.faqs (id, question, answer, category, sort_order) values
  ($$what-is-bidawash$$, $$What is BidaWash?$$, $$BidaWash is a touchless automated car wash designed to provide a fast, convenient, and high-quality vehicle cleaning experience.$$, $$General$$, 10),
  ($$how-does-it-work$$, $$How does BidaWash work?$$, $$Simply drive into the wash bay, follow the on-site instructions, select your wash package, make your payment, and allow the automated system to clean your vehicle. Our on-site staff can also assist you and perform final spot checks when needed.$$, $$General$$, 20),
  ($$how-is-it-different$$, $$How is BidaWash different from a traditional car wash?$$, $$BidaWash automates most of the exterior washing process using car-safe cleaning solutions, high-pressure water, sensors, and automated equipment. Our system is also 100% touchless, meaning no brushes or wash materials physically scrub against your vehicle. This allows us to provide a faster, more consistent wash while reducing manual labor and water consumption.$$, $$General$$, 30),
  ($$what-does-touchless-mean$$, $$What does "touchless" mean?$$, $$BidaWash uses a combination of car-safe cleaning solutions and high-pressure water to remove dirt without brushes or other wash equipment physically scrubbing the vehicle.$$, $$General$$, 40),
  ($$is-it-environmentally-friendly$$, $$Is BidaWash environmentally friendly?$$, $$Yes. BidaWash uses a water recycling system to significantly reduce fresh-water consumption compared with conventional car washing. We also use pH-neutral car wash solutions designed to clean vehicles effectively while being gentle on automotive surfaces.$$, $$General$$, 50),
  ($$before-entering-wash-bay$$, $$What should I do before entering the wash bay?$$, $$Close all windows, doors, sunroofs, and convertible roofs. Fold or secure accessories where applicable, turn off automatic wipers, and follow all instructions given by our staff or displayed at the wash bay.$$, $$Wash Process$$, 60),
  ($$gear-position-during-wash$$, $$Should my vehicle be in Park, Neutral, or Drive during the wash?$$, $$Keep your vehicle in Park throughout the wash. The BidaWash machine moves around your stationary vehicle, so there is no need for the vehicle itself to move during the wash cycle.$$, $$Wash Process$$, 70),
  ($$can-i-leave-vehicle$$, $$Can I leave my vehicle during the wash?$$, $$You may exit the vehicle before the wash begins if instructed or permitted by our staff. However, once the wash cycle has started, you must not enter or exit the vehicle until the wash is complete.$$, $$Wash Process$$, 80),
  ($$wash-duration$$, $$How long does a wash take?$$, $$The exact wash time depends on the package selected. BidaWash is designed to provide a complete exterior wash in approximately 10 minutes.$$, $$Wash Process$$, 90),
  ($$power-outage-during-wash$$, $$What happens if the machine stops or there is a power outage during my wash?$$, $$If the machine stops because of a system fault, safety condition, or power outage, remain safely in your vehicle and follow instructions from the BidaWash team. Our staff will assess the situation and determine whether the wash can safely continue or whether the vehicle should be guided out of the bay.$$, $$Equipment & Safety$$, 100),
  ($$deluxe-foam-inclusions$$, $$What is included in the Deluxe Foam Wash?$$, $$The Deluxe Foam Wash includes an under-chassis wash, pre-soak, shampoo wash, high-pressure rinse, and drying.$$, $$Wash Packages & Results$$, 110),
  ($$premium-wax-inclusions$$, $$What is included in the Premium Wax Wash?$$, $$The Premium Wax Wash includes an under-chassis wash, pre-soak, shampoo wash, high-pressure rinse, wax application, and drying.$$, $$Wash Packages & Results$$, 120),
  ($$will-vehicle-be-clean$$, $$Will my vehicle be completely clean after the wash?$$, $$The BidaWash machine is designed to clean approximately 99% of the vehicle under normal washing conditions, making it suitable for thoroughly cleaning the vast majority of vehicles. We also anticipate that certain areas or unusual dirt may occasionally need extra attention, which is why our team performs spot checks and final touches on every vehicle before it leaves the bay.$$, $$Wash Packages & Results$$, 130),
  ($$wash-satisfaction$$, $$What if I am not satisfied with the wash result?$$, $$Please let our on-site team know immediately. We inspect every vehicle after the automated wash and can perform additional spot cleaning or final touches where needed. Our goal is to make sure you leave satisfied with the result.$$, $$Wash Packages & Results$$, 140),
  ($$underside-cleaning$$, $$Does BidaWash clean the underside of the vehicle?$$, $$Yes. All BidaWash wash packages include an under-chassis wash, which uses water jets to rinse dirt and contaminants from accessible areas underneath the vehicle.$$, $$Wash Packages & Results$$, 150),
  ($$compatible-vehicles$$, $$What vehicles can use BidaWash?$$, $$Most sedans, hatchbacks, crossovers, SUVs, pickup trucks, and compatible vans can use BidaWash as long as they meet our size limits and vehicle compatibility requirements.$$, $$Vehicle Compatibility$$, 160),
  ($$vehicle-size-limits$$, $$What is the maximum vehicle size allowed?$$, $$Vehicles must be below 2.0 meters in height, 5.5 meters in length, and 2.0 meters in width. Vehicles must also be in safe operating condition and meet our compatibility requirements.$$, $$Vehicle Compatibility$$, 170),
  ($$pickup-truck-convertible$$, $$Can pickup trucks and convertibles use BidaWash?$$, $$Yes, provided the vehicle meets our size and compatibility requirements. Convertible roofs, windows, seals, and locking mechanisms must be fully closed and in good condition. Pickup trucks may retain some water in the truck bed after washing, particularly around drainage channels and recessed areas.$$, $$Vehicle Compatibility$$, 180),
  ($$ceramic-ppf-wraps$$, $$Is BidaWash safe for ceramic coatings, PPF, wraps, and decals?$$, $$Yes, properly installed and well-maintained ceramic coatings, PPF, wraps, and decals are generally compatible with touchless washing because no brushes physically scrub the vehicle. However, damaged, peeling, lifting, or poorly installed films or decals may be affected by high-pressure water.$$, $$Vehicle Compatibility$$, 190),
  ($$modified-vehicles$$, $$Can modified vehicles, lowered vehicles, or vehicles with roof racks use BidaWash?$$, $$It depends on the modification. Vehicles with altered dimensions, protruding accessories, loose parts, very low ground clearance, oversized tires, roof boxes, bike racks, or other significant modifications may not be compatible with the wash. Our staff may inspect the vehicle before allowing entry.$$, $$Vehicle Compatibility$$, 200),
  ($$ev-hybrid-safe$$, $$Is BidaWash safe for electric and hybrid vehicles?$$, $$Yes. Electric and hybrid vehicles can safely use automatic car washes when the vehicle manufacturer's instructions are followed. Modern EV battery systems and high-voltage components are designed to withstand normal road exposure to water.$$, $$Vehicle Compatibility$$, 210),
  ($$payment-methods$$, $$What payment methods do you accept?$$, $$BidaWash is cashless. We accept supported credit and debit cards as well as QRPh-compatible e-wallet payments. BidaWash locations also provide on-site internet access to help customers complete supported digital payments.$$, $$Payments & Refunds$$, 220),
  ($$charge-without-wash$$, $$What happens if I was charged but the wash did not start?$$, $$Please inform our on-site staff or contact BidaWash support immediately. Once the transaction is verified, we may provide a rewash, wash credit, or refund depending on the circumstances.$$, $$Payments & Refunds$$, 230),
  ($$locations-and-hours$$, $$Where are your locations and what are your operating hours?$$, $$BidaWash operates daily from 8:00 AM to 7:00 PM. Our current and upcoming locations are listed on the BidaWash app, bidawash.com, and our official Facebook, Instagram, and TikTok pages at @bidawashph.$$, $$Locations & Operating Hours$$, 240),
  ($$memberships-and-discounts$$, $$Do you offer memberships, corporate rates, or discounts?$$, $$Memberships, wash bundles, subscriptions, loyalty rewards, and promotional discounts may be introduced from time to time. We also welcome corporate partnerships, fleet arrangements, and volume-based programs. Companies interested in working with BidaWash can contact support@bidawash.com.$$, $$Memberships & Promotions$$, 250)
on conflict (id) do update set
  question   = excluded.question,
  answer     = excluded.answer,
  category   = excluded.category,
  sort_order = excluded.sort_order;
